//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chiota.Resources.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chiota.Resources.Localizations.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string CmnAbout {
            get {
                return ResourceManager.GetString("CmnAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add contact.
        /// </summary>
        internal static string CmnAddContact {
            get {
                return ResourceManager.GetString("CmnAddContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back up.
        /// </summary>
        internal static string CmnBackUp {
            get {
                return ResourceManager.GetString("CmnBackUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chats.
        /// </summary>
        internal static string CmnChats {
            get {
                return ResourceManager.GetString("CmnChats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm seed.
        /// </summary>
        internal static string CmnConfirmSeed {
            get {
                return ResourceManager.GetString("CmnConfirmSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact address.
        /// </summary>
        internal static string CmnContactAddress {
            get {
                return ResourceManager.GetString("CmnContactAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact request.
        /// </summary>
        internal static string CmnContactRequest {
            get {
                return ResourceManager.GetString("CmnContactRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string CmnContacts {
            get {
                return ResourceManager.GetString("CmnContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string CmnEdit {
            get {
                return ResourceManager.GetString("CmnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string CmnHelp {
            get {
                return ResourceManager.GetString("CmnHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string CmnLogOut {
            get {
                return ResourceManager.GetString("CmnLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Contact.
        /// </summary>
        internal static string CmnNewContact {
            get {
                return ResourceManager.GetString("CmnNewContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New seed.
        /// </summary>
        internal static string CmnNewSeed {
            get {
                return ResourceManager.GetString("CmnNewSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print paper copy.
        /// </summary>
        internal static string CmnPrintPaperCopy {
            get {
                return ResourceManager.GetString("CmnPrintPaperCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Privacy Policy.
        /// </summary>
        internal static string CmnPrivacyPolicy {
            get {
                return ResourceManager.GetString("CmnPrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR code.
        /// </summary>
        internal static string CmnQrCode {
            get {
                return ResourceManager.GetString("CmnQrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string CmnSearch {
            get {
                return ResourceManager.GetString("CmnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string CmnSetPassword {
            get {
                return ResourceManager.GetString("CmnSetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set seed.
        /// </summary>
        internal static string CmnSetSeed {
            get {
                return ResourceManager.GetString("CmnSetSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string CmnSettings {
            get {
                return ResourceManager.GetString("CmnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set user.
        /// </summary>
        internal static string CmnSetUser {
            get {
                return ResourceManager.GetString("CmnSetUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write seed down.
        /// </summary>
        internal static string CmnWriteSeedDown {
            get {
                return ResourceManager.GetString("CmnWriteSeedDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string DlgAccept {
            get {
                return ResourceManager.GetString("DlgAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding contact.
        /// </summary>
        internal static string DlgAddContact {
            get {
                return ResourceManager.GetString("DlgAddContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string DlgAddress {
            get {
                return ResourceManager.GetString("DlgAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved..
        /// </summary>
        internal static string DlgAllRightsReserved {
            get {
                return ResourceManager.GetString("DlgAllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string DlgCancel {
            get {
                return ResourceManager.GetString("DlgCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string DlgContinue {
            get {
                return ResourceManager.GetString("DlgContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        internal static string DlgDecline {
            get {
                return ResourceManager.GetString("DlgDecline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete account.
        /// </summary>
        internal static string DlgDeleteAccount {
            get {
                return ResourceManager.GetString("DlgDeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must back up your seed with at least one of the options listed below..
        /// </summary>
        internal static string DlgDescBackUp {
            get {
                return ResourceManager.GetString("DlgDescBackUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your seed..
        /// </summary>
        internal static string DlgDescConfirmSeed {
            get {
                return ResourceManager.GetString("DlgDescConfirmSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in with your password..
        /// </summary>
        internal static string DlgDescLogIn {
            get {
                return ResourceManager.GetString("DlgDescLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the button to generate a new seed. Click single characters of the seed to change them individually..
        /// </summary>
        internal static string DlgDescNewSeed {
            get {
                return ResourceManager.GetString("DlgDescNewSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please print your seed and keep it safe..
        /// </summary>
        internal static string DlgDescPrintPaperCopy {
            get {
                return ResourceManager.GetString("DlgDescPrintPaperCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please save your QR code and keep it safe..
        /// </summary>
        internal static string DlgDescQrCode {
            get {
                return ResourceManager.GetString("DlgDescQrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate up and down, to see the full seed..
        /// </summary>
        internal static string DlgDescSeedView {
            get {
                return ResourceManager.GetString("DlgDescSeedView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a new password to save your personal data on this device..
        /// </summary>
        internal static string DlgDescSetPassword {
            get {
                return ResourceManager.GetString("DlgDescSetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert your seed to get access to an existing account..
        /// </summary>
        internal static string DlgDescSetSeed {
            get {
                return ResourceManager.GetString("DlgDescSetSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert your name and click on the profile image to upload a new one..
        /// </summary>
        internal static string DlgDescSetUser {
            get {
                return ResourceManager.GetString("DlgDescSetUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a new seed to create an account or set a seed to get access to an existing..
        /// </summary>
        internal static string DlgDescWelcome {
            get {
                return ResourceManager.GetString("DlgDescWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write your seed down and keep it safe..
        /// </summary>
        internal static string DlgDescWriteSeedDown {
            get {
                return ResourceManager.GetString("DlgDescWriteSeedDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New seed.
        /// </summary>
        internal static string DlgGenerateSeed {
            get {
                return ResourceManager.GetString("DlgGenerateSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got it.
        /// </summary>
        internal static string DlgGotIt {
            get {
                return ResourceManager.GetString("DlgGotIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is a contact address?.
        /// </summary>
        internal static string DlgHelpContactAddress {
            get {
                return ResourceManager.GetString("DlgHelpContactAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is a seed?.
        /// </summary>
        internal static string DlgHelpSeed {
            get {
                return ResourceManager.GetString("DlgHelpSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your seed is the master key to your account. It is 81 characters long, using only letters A-Z or the number 9..
        /// </summary>
        internal static string DlgHelpSeedDesc0 {
            get {
                return ResourceManager.GetString("DlgHelpSeedDesc0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use it to access your account from any device, where Chiota is installed..
        /// </summary>
        internal static string DlgHelpSeedDesc1 {
            get {
                return ResourceManager.GetString("DlgHelpSeedDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you lose your seed, you also lose access to your account..
        /// </summary>
        internal static string DlgHelpSeedDesc2 {
            get {
                return ResourceManager.GetString("DlgHelpSeedDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Least secure.
        /// </summary>
        internal static string DlgLeastSecure {
            get {
                return ResourceManager.GetString("DlgLeastSecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string DlgLoading {
            get {
                return ResourceManager.GetString("DlgLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging you in.
        /// </summary>
        internal static string DlgLoggingIn {
            get {
                return ResourceManager.GetString("DlgLoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string DlgLogIn {
            get {
                return ResourceManager.GetString("DlgLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string DlgMessage {
            get {
                return ResourceManager.GetString("DlgMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most secure.
        /// </summary>
        internal static string DlgMostSecure {
            get {
                return ResourceManager.GetString("DlgMostSecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string DlgName {
            get {
                return ResourceManager.GetString("DlgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I need a seed.
        /// </summary>
        internal static string DlgNewSeed {
            get {
                return ResourceManager.GetString("DlgNewSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string DlgOk {
            get {
                return ResourceManager.GetString("DlgOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string DlgPassword {
            get {
                return ResourceManager.GetString("DlgPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat password.
        /// </summary>
        internal static string DlgRepeatPassword {
            get {
                return ResourceManager.GetString("DlgRepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string DlgSave {
            get {
                return ResourceManager.GetString("DlgSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as QR Code.
        /// </summary>
        internal static string DlgSaveQrCode {
            get {
                return ResourceManager.GetString("DlgSaveQrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan QR code.
        /// </summary>
        internal static string DlgScanQrCode {
            get {
                return ResourceManager.GetString("DlgScanQrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seed.
        /// </summary>
        internal static string DlgSeed {
            get {
                return ResourceManager.GetString("DlgSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have a seed.
        /// </summary>
        internal static string DlgSetSeed {
            get {
                return ResourceManager.GetString("DlgSetSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting up your account.
        /// </summary>
        internal static string DlgSettingUpAccount {
            get {
                return ResourceManager.GetString("DlgSettingUpAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string DlgVersion {
            get {
                return ResourceManager.GetString("DlgVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write seed down.
        /// </summary>
        internal static string DlgWriteSeedDown {
            get {
                return ResourceManager.GetString("DlgWriteSeedDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New contact.
        /// </summary>
        internal static string NotifyNewContact {
            get {
                return ResourceManager.GetString("NotifyNewContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New contact request.
        /// </summary>
        internal static string NotifyNewContactRequest {
            get {
                return ResourceManager.GetString("NotifyNewContactRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string SettingsAbout {
            get {
                return ResourceManager.GetString("SettingsAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite friends.
        /// </summary>
        internal static string SettingsInviteFriends {
            get {
                return ResourceManager.GetString("SettingsInviteFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string SettingsProfile {
            get {
                return ResourceManager.GetString("SettingsProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        internal static string SettingsSecurity {
            get {
                return ResourceManager.GetString("SettingsSecurity", resourceCulture);
            }
        }
    }
}
