using Chiota.ViewModels;

namespace Chiota.Views
{
  using System;

  using Chiota.Services.DependencyInjection;
  using Chiota.ViewModels;

  using Xamarin.Forms;
  using Xamarin.Forms.Xaml;

  /// <summary>
  /// The add contact.
  /// </summary>
  [XamlCompilation(XamlCompilationOptions.Compile)]
  public partial class AddContactView : ContentPage
  {
    // adds your contact automaticly to some elses contact list in form of an adress generated by yourself
    public AddContactView()
    {
      this.InitializeComponent();

      var vm = DependencyResolver.Resolve<AddContactViewModel>(); 
      vm.Navigation = this.Navigation;

      this.ReceiverAdress.Completed += (object sender, EventArgs e) =>
        {
          vm.SubmitCommand.Execute(null);
        };
      this.BindingContext = vm;
    }

    private void AddressTapHandle(object sender, EventArgs e)
    {
      (this.BindingContext as AddContactViewModel)?.AddAdressToClipboard();
      this.DisplayAlert("Copied", "The address has been copied to your clipboard.", "OK");
    }
  }
}