namespace Chiota.Views
{
  using System;

  using Chiota.Models;
  using Chiota.ViewModels;

  using Xamarin.Forms;
  using Xamarin.Forms.Xaml;

  [XamlCompilation(XamlCompilationOptions.Compile)]
  public partial class AddContact : ContentPage
  {
    // adds your contact automaticly to some elses contact list in form of an adress generated by yourself
    public AddContact(User user)
    {
      this.InitializeComponent();
      var vm = new AddContactViewModel(user);

      vm.DisplayInvalidAdressPrompt += () => this.DisplayAlert("Error", "Invalid adress, try again", "OK");

      this.ReceiverAdress.Completed += (object sender, EventArgs e) =>
        {
          vm.SubmitCommand.Execute(null);
        };
      this.BindingContext = new AddContactViewModel(user);
    }

    private void AdressTapHandle(object sender, EventArgs e)
    {
      (this.BindingContext as AddContactViewModel)?.AddAdressToClipboard();
      this.DisplayAlert("Copied", "The address has been copied to your clipboard.", "OK");
    }
  }
}