namespace Chiota.Views
{
  using Chiota.Models;
  using Chiota.ViewModels;

  using Xamarin.Forms;
  using Xamarin.Forms.Xaml;

  /// <summary>
  /// The add contact.
  /// </summary>
  [XamlCompilation(XamlCompilationOptions.Compile)]
  public partial class SettingsPage : ContentPage
  {
    // adds your contact automaticly to some elses contact list in form of an adress generated by yourself
    public SettingsPage()
    {
      this.InitializeComponent();
      var vm = new SettingsViewModel { Navigation = this.Navigation };
      vm.DisplayInvalidNodePrompt += () => this.DisplayAlert("Error", "Invalid Node, try again", "OK");
      vm.DisplaySettingsChangedPrompt += () => this.DisplayAlert("Saved", "Settings successfully updated", "OK");
      this.BindingContext = vm;
    }
  }
}