using Chiota.ViewModels;

namespace Chiota.Views
{
  using System;

  using Chiota.Messenger.Repository;
  using Chiota.Messenger.Service;
  using Chiota.Messenger.Usecase.AddContact;
  using Chiota.Models;
  using Chiota.Persistence;
  using Chiota.Services.DependencyInjection;
  using Chiota.Services.Iota.Repository;
  using Chiota.ViewModels;

  using Xamarin.Forms;
  using Xamarin.Forms.Xaml;

  /// <summary>
  /// The add contact.
  /// </summary>
  [XamlCompilation(XamlCompilationOptions.Compile)]
  public partial class AddContactPage : ContentPage
  {
    // adds your contact automaticly to some elses contact list in form of an adress generated by yourself
    public AddContactPage()
    {
      this.InitializeComponent();
      var iotaRepository = DependencyResolver.Resolve<IRepositoryFactory>().Create();
      var vm = new AddContactViewModel(
                 new AddContactInteractor(
                   DependencyResolver.Resolve<AbstractSqlLiteDb>(),
                   new TangleMessenger(iotaRepository),
                   new TangleContactInformationRepository(iotaRepository))) { Navigation = this.Navigation };

      this.ReceiverAdress.Completed += (object sender, EventArgs e) =>
        {
          vm.SubmitCommand.Execute(null);
        };
      this.BindingContext = vm;
    }

    private void AddressTapHandle(object sender, EventArgs e)
    {
      (this.BindingContext as AddContactViewModel)?.AddAdressToClipboard();
      this.DisplayAlert("Copied", "The address has been copied to your clipboard.", "OK");
    }
  }
}