#region Directives
using System;
using System.Threading.Tasks;
using VTDev.Libraries.CEXEngine.Crypto.Common;
using VTDev.Libraries.CEXEngine.Crypto.Enumeration;
using VTDev.Libraries.CEXEngine.CryptoException;
using VTDev.Libraries.CEXEngine.Utility;
#endregion

#region License Information
// The MIT License (MIT)
// 
// Copyright (c) 2016 vtdev.com
// This file is part of the CEX Cryptographic library.
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// 
// Implementation Details:
// An implementation of an segmented Counter Mode (CTR).
// Written by John Underhill, September 24, 2014
// Updated October 8, 2016
// Contact: develop@vtdev.com
#endregion

namespace VTDev.Libraries.CEXEngine.Crypto.Cipher.Symmetric.Block.Mode
{
    /// <summary>
    /// Implements a big endian segmented integer Counter Mode (CTR)
    /// </summary> 
    /// 
    /// <example>
    /// <description>Encrypting a single block of bytes:</description>
    /// <code>
    /// using (ICipherMode cipher = new CTR(BlockCiphers.RHX))
    /// {
    ///     // initialize for encryption
    ///     cipher.Initialize(true, new KeyParams(Key, IV));
    ///     // encrypt a block
    ///     cipher.Transform(Input, 0, Output, 0);
    /// }
    /// </code>
    /// </example>
    /// 
    /// <remarks>
    /// <description><B>Overview:</B></description>
    /// <para>The CTR Counter mode generates a key-stream by encrypting successive values of an incrementing Big Endian ordered 8bit integer counter array.<BR></BR>
    /// The key-stream is then XOR'd with the input message block creating a type of stream cipher.<BR></BR>
    /// In parallel mode, the CTR modes counter is increased by a number factored from the number of message blocks (ParallelBlockSize), allowing for counter pre-calculation and multi-threaded processing.</para>
    /// 
    /// <description><B>Description:</B></description>
    /// <para><EM>Legend:</EM><BR></BR> 
    /// <B>C</B>=ciphertext, <B>P</B>=plaintext, <B>K</B>=key, <B>E</B>=encrypt, <B>^</B>=XOR<BR></BR><BR></BR>
    /// <EM>Encryption</EM><BR></BR>
    /// C0 ← IV. For 1 ≤ j ≤ t, Cj ← EK(Cj) ^ Pj, C+1.</para><BR></BR>
    ///
    /// <description><B>Multi-Threading:</B></description>
    /// <para>The transformation function of the CTR mode is not limited by a dependency chain; this mode can be both SIMD pipelined and multi-threaded.
    /// Output from the parallelized functions aligns with the output from a standard sequential CTR implementation.<BR></BR>
    /// This is acheived by pre-calculating the counters positional offset over multiple 'chunks' of key-stream, which are then generated independently across threads.<BR></BR> 
    /// The key stream generated by encrypting the counter array(s), is used as a source of random, and XOR'd with the message input to produce the cipher text.</para>
    ///
    /// <description>Implementation Notes:</description>
    /// <list type="bullet">
    /// <item><description>In CTR mode, Encryption/Decryption can both be pipelined (SSE3-128 or AVX-256), and multi-threaded.</description></item>
    /// <item><description>A cipher mode constructor can either be initialized with a block cipher instance, or using the block ciphers enumeration name.</description></item>
    /// <item><description>A block cipher instance created using the enumeration constructor, is automatically deleted when the class is destroyed.</description></item>
    /// <item><description>The Transform functions are virtual, and can be accessed from an ICipherMode instance.</description></item>
    /// <item><description>The EncryptBlock function can only be accessed through the class instance.</description></item>
    /// <item><description>The transformation methods can not be called until the Initialize(bool, KeyParams) function has been called.</description></item>
    /// <item><description>The IsParallel property is enabled automatically if the system has more than one processor core.</description></item>
    /// <item><description>Parallel processing is enabled when the IsParallel property is set to true, and an input block of ParallelBlockSize is passed to the transform.</description></item>
    /// <item><description>The ParallelOptions.MaxDegreeOfParallelism property can be used to modify the thread count in the parallel loop; this must be an even number no greater than the number of processer cores on the system.</description></item>
    /// <item><description>ParallelBlockSize is calculated automatically but can be user defined, but must be evenly divisible by ParallelMinimumSize.</description></item>
    /// <item><description>Parallel block calculation ex. <c>ParallelBlockSize = (data.Length / cipher.ParallelMinimumSize) * 40</c></description></item>
    /// </list>
    /// 
    /// <description>Guiding Publications:</description>
    /// <list type="number">
    /// <item><description>NIST <a href="http://csrc.nist.gov/publications/nistpubs/800-38a/sp800-38a.pdf">SP800-38A</a>.</description></item>
    /// <item><description>Handbook of Applied Cryptography <a href="http://cacr.uwaterloo.ca/hac/about/chap7.pdf">Chapter 7: Block Ciphers</a>.</description></item>
    /// </list>
    /// </remarks>
    public sealed class CTR : ICipherMode
    {
        #region Constants
        private const string ALG_NAME = "CTR";
        private const int BLOCK_SIZE = 1024;
        private const int MAXALLOC_MB100 = 100000000;
        private const int PRL_BLOCKCACHE = 32000;
        #endregion

        #region Fields
        private IBlockCipher m_blockCipher;
        private int m_blockSize = 0;
        private byte[] m_ctrVector;
        private bool m_disposeEngine = false;
        private bool m_isDisposed = false;
        private bool m_isEncryption = false;
        private bool m_isInitialized = false;
        private bool m_isLoaded = false;
        private bool m_isParallel = false;
        private int m_parallelBlockSize = 0;
        private int m_parallelMinimumSize = 0;
        private ParallelOptions m_parallelOption = null;
        private int m_processorCount = 1;
        #endregion

        #region Properties
        /// <summary>
        /// Get: Unit block size of internal cipher
        /// </summary>
        public int BlockSize
        {
            get { return m_blockSize; }
            private set { m_blockSize = value; }
        }

        /// <summary>
        /// Get: Underlying Cipher
        /// </summary>
        public IBlockCipher Engine
        {
            get { return m_blockCipher; }
            private set { m_blockCipher = value; }
        }

        /// <summary>
        /// Get: The cipher modes type name
        /// </summary>
        public CipherModes Enumeral
        {
            get { return CipherModes.CTR; }
        }

        /// <summary>
        /// Get: Initialized for encryption, false for decryption
        /// </summary>
        public bool IsEncryption
        {
            get { return m_isEncryption; }
            private set { m_isEncryption = value; }
        }

        /// <summary>
        /// Get: Cipher is ready to transform data
        /// </summary>
        public bool IsInitialized
        {
            get { return m_isInitialized; }
            private set { m_isInitialized = value; }
        }

        /// <summary>
        /// Get/Set: Automatic processor parallelization
        /// </summary>
        public bool IsParallel
        {
            get { return m_isParallel; }
            set { m_isParallel = value; }
        }

        /// <summary>
        /// Get: The current state of the initialization Vector
        /// </summary>
        public byte[] IV
        {
            get { return (byte[])m_ctrVector.Clone(); }
        }

        /// <summary>
        /// Get: Cipher name
        /// </summary>
        public string Name
        {
            get { return ALG_NAME; }
        }

        /// <summary>
        /// Get/Set: Parallel block size. Must be a multiple of <see cref="ParallelMinimumSize"/>.
        /// </summary>
        /// 
        /// <exception cref="CryptoSymmetricException">Thrown if a parallel block size is not evenly divisible by ParallelMinimumSize, or  block size is less than ParallelMinimumSize or more than ParallelMaximumSize values</exception>
        public int ParallelBlockSize
        {
            get { return m_parallelBlockSize; }
            set
            {
                if (value % ParallelMinimumSize != 0)
                    throw new CryptoSymmetricException("CTR:ParallelBlockSize", String.Format("Parallel block size must be evenly divisible by ParallelMinimumSize: {0}", ParallelMinimumSize), new ArgumentException());
                if (value > ParallelMaximumSize || value < ParallelMinimumSize)
                    throw new CryptoSymmetricException("CTR:ParallelBlockSize", String.Format("Parallel block must be Maximum of ParallelMaximumSize: {0} and evenly divisible by ParallelMinimumSize: {1}", ParallelMaximumSize, ParallelMinimumSize), new ArgumentOutOfRangeException());

                m_parallelBlockSize = value;
            }
        }

        /// <summary>
        /// Get: Maximum input size with parallel processing
        /// </summary>
        public int ParallelMaximumSize
        {
            get { return MAXALLOC_MB100; }
        }

        /// <summary>
        /// Get: The smallest parallel block size. Parallel blocks must be a multiple of this size.
        /// </summary>
        public int ParallelMinimumSize
        {
            get { return m_parallelMinimumSize; }
        }
        
        /// <summary>
        /// Get/Set: The parallel loops ParallelOptions
        /// <para>The MaxDegreeOfParallelism of the parallel loop is equal to the Environment.ProcessorCount by default</para>
        /// </summary>
        public ParallelOptions ParallelOption
        {
            get
            {
                if (m_parallelOption == null)
                    m_parallelOption = new ParallelOptions() { MaxDegreeOfParallelism = Environment.ProcessorCount };

                return m_parallelOption;
            }
            set
            {
                if (value != null)
                {
                    if (value.MaxDegreeOfParallelism < 1)
                        throw new CryptoSymmetricException("CTR:ParallelOption", "MaxDegreeOfParallelism can not be less than 1!", new ArgumentException());
                    else if (value.MaxDegreeOfParallelism == 1)
                        m_isParallel = false;
                    else if (value.MaxDegreeOfParallelism % 2 != 0)
                        throw new CryptoSymmetricException("CTR:ParallelOption", "MaxDegreeOfParallelism can not be an odd number; must be either 1, or a divisible of 2!", new ArgumentException());

                    m_parallelOption = value;
                }
            }
        }

        /// <remarks>
        /// Get: Processor count
        /// </remarks>
        private int ProcessorCount
        {
            get { return m_processorCount; }
            set { m_processorCount = value; }
        }
        #endregion

        #region Constructor
        /// <summary>
        /// Initialize the cipher mode using a block cipher type name
        /// </summary>
        /// 
        /// <param name="CipherType">The formal enumeration name of a block cipher</param>
        /// 
        /// <exception cref="System.ArgumentNullException">Thrown if an invalid Cipher type is used</exception>
        public CTR(BlockCiphers CipherType)
        {
            if (CipherType == BlockCiphers.None)
                throw new CryptoSymmetricException("CTR:CTor", "The Cipher type can not be none!", new ArgumentNullException());

            m_disposeEngine = true;
            m_blockCipher = LoadCipher(CipherType);
            m_blockSize = m_blockCipher.BlockSize;
            Scope();
        }

        /// <summary>
        /// Initialize the cipher mode with a block cipher instance
        /// </summary>
        /// 
        /// <param name="Cipher">Underlying encryption algorithm</param>
        /// <param name="DisposeEngine">Dispose of digest engine when <see cref="Dispose()"/> on this class is called</param>
        /// 
        /// <exception cref="CryptoSymmetricException">Thrown if a null Cipher is used</exception>
        public CTR(IBlockCipher Cipher, bool DisposeEngine = true)
        {
            if (Cipher == null)
                throw new CryptoSymmetricException("CTR:CTor", "The Cipher can not be null!", new ArgumentNullException());

            m_disposeEngine = DisposeEngine;
            m_blockCipher = Cipher;
            m_blockSize = m_blockCipher.BlockSize;
            Scope();
        }

        private CTR()
        {
        }

        /// <summary>
        /// Finalize objects
        /// </summary>
        ~CTR()
        {
            Dispose(false);
        }
        #endregion

        #region Public Methods
        /// <summary>
        /// Encrypt a block of bytes. 
        /// <para><see cref="Initialize(bool, KeyParams)"/> must be called before this method can be used.</para>
        /// </summary>
        /// 
        /// <param name="Input">Bytes to Encrypt</param>
        /// <param name="Output">Encrypted bytes</param>
        void EncryptBlock(byte[] Input, byte[] Output)
        {
            EncryptBlock(Input, 0, Output, 0);
        }

        /// <summary>
        /// Encrypt a block of bytes with offset parameters. 
        /// <para><see cref="Initialize(bool, KeyParams)"/> must be called before this method can be used.</para>
        /// </summary>
        /// 
        /// <param name="Input">Bytes to Encrypt</param>
        /// <param name="InOffset">Offset in the Input array</param>
        /// <param name="Output">Encrypted bytes</param>
        /// <param name="OutOffset">Offset in the Output array</param>
        void EncryptBlock(byte[] Input, int InOffset, byte[] Output, int OutOffset)
        {
            m_blockCipher.EncryptBlock(m_ctrVector, 0, Output, OutOffset);
            Increment(m_ctrVector);

            for (int i = 0; i < m_ctrVector.Length; ++i)
                Output[i + OutOffset] ^= Input[i + InOffset];
        }

        /// <summary>
        /// Initialize the Cipher
        /// </summary>
        /// 
        /// <param name="Encryption">True if cipher is used for encryption, false to decrypt</param>
        /// <param name="KeyParam">The KeyParams containing key and vector</param>
        /// 
        /// <exception cref="CryptoSymmetricException">Thrown if a null Key or IV is used</exception>
        public void Initialize(bool Encryption, KeyParams KeyParam)
        {
            // recheck params
            Scope();

            if (KeyParam.Key == null)
                throw new CryptoSymmetricException("CTR:Initialize", "Key can not be null!", new ArgumentNullException());
            if (KeyParam.IV == null)
                throw new CryptoSymmetricException("CTR:Initialize", "IV can not be null!", new ArgumentNullException());
            if (IsParallel && ParallelBlockSize < ParallelMinimumSize || ParallelBlockSize > ParallelMaximumSize)
                throw new CryptoSymmetricException("CTR:Initialize", "The parallel block size is out of bounds!");
            if (IsParallel && ParallelBlockSize % ParallelMinimumSize != 0)
                throw new CryptoSymmetricException("CTR:Initialize", "The parallel block size must be evenly aligned to the ParallelMinimumSize!");

            m_blockCipher.Initialize(true, KeyParam);
            m_ctrVector = KeyParam.IV;
            m_isEncryption = Encryption;
            m_isInitialized = true;
        }

        /// <summary>
        /// Transform one block of bytes. 
        /// <para>Parallel capable function if Output array length is at least equal to <see cref="ParallelMinimumSize"/>. 
        /// Method will process a single block from the array of either ParallelBlockSize or Blocksize depending on IsParallel property setting.
        /// Partial blocks are permitted with both parallel and linear operation modes. 
        /// If using this method, output and input arrays should be sized to ParallelBlockSize.
        /// <see cref="Initialize(bool, KeyParams)"/> must be called before this method can be used.</para>
        /// </summary>
        /// 
        /// <param name="Input">The input array of bytes to transform</param>
        /// <param name="Output">The output array of transformed bytes</param>
        public void Transform(byte[] Input, byte[] Output)
        {
            Transform(Input, 0, Output, 0);
        }

        /// <summary>
        /// Transform one block of bytes with offset parameters.  
        /// <para>Parallel capable function if Output array length is at least equal to <see cref="ParallelMinimumSize"/>. 
        /// Method will process a single block from the array of either ParallelBlockSize or Blocksize depending on IsParallel property setting.
        /// Partial blocks are permitted with both parallel and linear operation modes.
        /// <see cref="Initialize(bool, KeyParams)"/> must be called before this method can be used.</para>
        /// </summary>
        /// 
        /// <param name="Input">The input array of bytes to transform</param>
        /// <param name="InOffset">Starting offset within the input array</param>
        /// <param name="Output">The output array of transformed bytes</param>
        /// <param name="OutOffset">Starting offset within the output array</param>
        public void Transform(byte[] Input, int InOffset, byte[] Output, int OutOffset)
        {
            if (m_isParallel)
            {
                if (Output.Length - OutOffset >= m_parallelBlockSize)
                    TransformParallel(Input, InOffset, Output, OutOffset, m_parallelBlockSize);
                else
                    TransformSequential(Input, InOffset, Output, OutOffset, Output.Length - OutOffset);
            }
            else
            {
                if (Output.Length - OutOffset >= m_blockSize)
                    EncryptBlock(Input, InOffset, Output, OutOffset);
                else
                    TransformSequential(Input, InOffset, Output, OutOffset, Output.Length - OutOffset);
            }
        }
        #endregion

        #region Private Methods
        private void Generate(byte[] Output, int OutOffset, int Size, byte[] Counter)
        {
            int aln = Size - (Size % BlockSize);
            int ctr = 0;

            while (ctr != aln)
            {
                m_blockCipher.EncryptBlock(Counter, 0, Output, OutOffset + ctr);
                Increment(Counter);
                ctr += BlockSize;
            }

            if (ctr != Size)
            {
                byte[] outputBlock = new byte[BlockSize];
                m_blockCipher.EncryptBlock(Counter, outputBlock);
                int fnlSize = Size % BlockSize;
                Buffer.BlockCopy(outputBlock, 0, Output, OutOffset + (Size - fnlSize), fnlSize);
                Increment(Counter);
            }
        }

        private static void Increment(byte[] Counter)
        {
            int i = Counter.Length;
            while (--i >= 0 && ++Counter[i] == 0) { }
        }

        private static byte[] Increase(byte[] Counter, int Size)
        {
            int carry = 0;
            byte[] buffer = new byte[Counter.Length];
            int offset = buffer.Length - 1;
            byte[] cnt = BitConverter.GetBytes(Size);
            byte osrc, odst, ndst;
            Buffer.BlockCopy(Counter, 0, buffer, 0, Counter.Length);

            for (int i = offset; i > 0; i--)
            {
                odst = buffer[i];
                osrc = offset - i < cnt.Length ? cnt[offset - i] : (byte)0;
                ndst = (byte)(odst + osrc + carry);
                carry = ndst < odst ? 1 : 0;
                buffer[i] = ndst;
            }

            return buffer;
        }

        IBlockCipher LoadCipher(BlockCiphers CipherType)
        {
            try
            {
                return Helper.BlockCipherFromName.GetInstance(CipherType);
            }
            catch (Exception ex)
            {
                throw new CryptoSymmetricException("CTR:LoadCipher", "The block cipher could not be instantiated!", ex);
            }
        }

        private void TransformParallel(byte[] Input, int InOffset, byte[] Output, int OutOffset, int Length)
        {
            int outSize = Length;

            // parallel CTR processing //
            int cnkSize = m_parallelBlockSize / m_processorCount;
		    int rndSize = cnkSize * m_processorCount;
		    int subSize = cnkSize / m_blockSize;
            byte[] tmpCtr = new byte[m_ctrVector.Length];

            // create random, and xor to output in parallel
            System.Threading.Tasks.Parallel.For(0, m_processorCount, ParallelOption, i =>
            {
                // thread level counter
                byte[] thdCtr = new byte[m_ctrVector.Length];
                // offset counter by chunk size / block size
                thdCtr = Increase(m_ctrVector, subSize * i);
                // create random at offset position
                Generate(Output, OutOffset + (i * cnkSize), cnkSize, thdCtr);
                // xor with input at offset
			    IntUtils.XORBLK(Input, InOffset + (i * cnkSize), Output, OutOffset + (i * cnkSize), cnkSize);
                // store last counter
                if (i == m_processorCount - 1)
                    Buffer.BlockCopy(thdCtr, 0, tmpCtr, 0, tmpCtr.Length);
            });

            // copy the last counter position to class variable
            Buffer.BlockCopy(tmpCtr, 0, m_ctrVector, 0, m_ctrVector.Length);

            // last block processing
            int alnSze = cnkSize * m_processorCount;
            if (alnSze < outSize)
            {
                int fnlSize = outSize % alnSze;
                Generate(Output, alnSze, fnlSize, m_ctrVector);

                for (int i = alnSze; i < outSize; i++)
                    Output[i] ^= Input[i];
            }
        }

        void TransformSequential(byte[] Input, int InOffset, byte[] Output, int OutOffset, int Length)
        {
            // generate random
            Generate(Output, OutOffset, Length, m_ctrVector);
            // get block aligned
            int alnSze = Length - (Length % m_blockCipher.BlockSize);

	        if (alnSze != 0)
		        Utility.IntUtils.XORBLK(Input, InOffset, Output, OutOffset, alnSze);

	        // get the remaining bytes
	        if (alnSze != Length)
	        {
		        for (int i = alnSze; i < Length; ++i)
			        Output[i + OutOffset] ^= Input[i + InOffset];
	        }
        }

        void Scope()
        {
            m_processorCount = Environment.ProcessorCount;
            if (m_processorCount % 2 != 0)
                m_processorCount--;

            if (m_processorCount > 1)
            {
                if (m_parallelOption != null && m_parallelOption.MaxDegreeOfParallelism > 0 && (m_parallelOption.MaxDegreeOfParallelism % 2 == 0))
                    m_processorCount = m_parallelOption.MaxDegreeOfParallelism;
                else
                    m_parallelOption = new ParallelOptions() { MaxDegreeOfParallelism = m_processorCount };
            }

            m_parallelMinimumSize = m_processorCount * m_blockCipher.BlockSize;
            m_parallelBlockSize = m_processorCount * PRL_BLOCKCACHE;
            m_parallelBlockSize -= (m_parallelBlockSize % ParallelMinimumSize);

            if (!m_isLoaded)
            {
                m_isParallel = (m_processorCount > 1);
                m_isLoaded = true;
            }
        }
        #endregion

        #region IDispose
        /// <summary>
        /// Dispose of this class, and dependant resources
        /// </summary>
        public void Dispose()
                {
                    Dispose(true);
                    GC.SuppressFinalize(this);
                }

        private void Dispose(bool Disposing)
        {
            if (!m_isDisposed && Disposing)
            {
                try
                {
                    if (m_blockCipher != null && m_disposeEngine)
                        m_blockCipher.Dispose();

                    if (m_ctrVector != null)
                    {
                        Array.Clear(m_ctrVector, 0, m_ctrVector.Length);
                        m_ctrVector = null;
                    }

                    m_blockSize = 0;
                    m_parallelBlockSize = 0;
                    m_parallelOption = null;

                }
                finally
                {
                    m_isLoaded = false;
                    m_isDisposed = true;
                }
            }
        }
        #endregion
    }
}
